#!/bin/bash

function ensure_link {
  test -e "$2"
  if [[ $? == 0 ]]
  then
    mv $1 "$1.orig"
  fi
  test -L "$2" || ln -s "$1" "$2"
}

cd $HOME/.switch_dotfiles/stevemartin

unlink $HOME/.vim
unlink $HOME/.vimrc

ln -s ${PWD}/.vim $HOME/.vim
ln -s ${PWD}/.vim/vimrc $HOME/.vimrc

cd $HOME/.vim/
git submodule init
git submodule update

brew install vim --with-lua --with-ruby

